# Needs a separate file secrets.yaml with the following content
# wifi_ssid: SSID 
# wifi_pasisword: KEY

substitutions:
  device_name: SonoffS31Template
  friendly_name: Sonoff S31 Template

esphome:
  name: sonoffs31template
  platform: ESP8266
  board: esp8285 
  build_path: ESPHome${device_name}

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  use_address: ${device_name}.local
#  use_address: 10.0.0.211

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHomeFallback"
    password: "cvTkuSHWqSIe"

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

captive_portal:

# Enable Home Assistant API
api:

ota:
  platform: esphome

web_server:
  port: 80

#######################################
# Device specific Config Begins Below #
#######################################

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name}: Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_name}: Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name}: WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime
  - platform: cse7766
    current:
      name: "${friendly_name}: Current"
      accuracy_decimals: 1
    voltage:
      name: "${friendly_name}: Voltage"
      accuracy_decimals: 1
    power:
      name: "${friendly_name}: Power"
      accuracy_decimals: 1
      id: my_power
  - platform: total_daily_energy
    name: "${friendly_name}: Daily Energy"
    power_id: my_power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kW

switch:
  - platform: gpio
    name: "${friendly_name}"
    icon: "mdi:power-socket-us"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: sntp
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: true

