# Needs a separate file secrets.yaml with the following content
# wifi_ssid: SSID 
# wifi_password: KEY

esphome:
  name: garagesensor 
  platform: ESP8266
  board: huzzah
  build_path: ESPHomeGarageSensor

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  use_address: GarageSensor.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperaturehumiditysensor"
    password: "cvTkuSHWqSIe"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht 
    pin: 2
    model: DHT22
    temperature:
      name: "Garage Temperature"
    humidity:
      name: "Garage Humidity"
    update_interval: 60s
