# Needs a separate file secrets.yaml with the following content
# wifi_ssid: SSID 
# wifi_pasisword: KEY

substitutions:
  device_name: GarageDoorController 
  friendly_name: Garage Door Controller
  id_prefix: ratgdov25
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

esphome:
  name: garagedoorcontroller 
  build_path: ESPHome${device_name}
  project:
    name: ratgdo.esphome
    version: "2.5"

esp8266:
  board: d1_mini_lite
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  use_address: ${device_name}.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHomeFallback"
    password: "cvTkuSHWqSIe"

captive_portal:

# Enable logging
logger:

improv_serial:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime

#######################################
# Device specific Config Begins Below #
#######################################

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini_lite.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
